# Generated by Django 4.2.1 on 2023-05-04 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main", models.CharField(max_length=30)),
                ("complement", models.CharField(max_length=30)),
                ("postal_code", models.CharField(max_length=30)),
                ("city", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="InstructorData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("graduation_date", models.DateField()),
                ("course_name", models.CharField(max_length=30)),
                ("institution_name", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("birth_date", models.DateField()),
                (
                    "profile",
                    models.CharField(
                        choices=[
                            ("STU", "Student"),
                            ("EMP", "Employee"),
                            ("PIL", "Pilot"),
                            ("INS", "Instructor"),
                        ],
                        max_length=3,
                    ),
                ),
                ("login", models.CharField(max_length=30, unique=True)),
                ("password", models.CharField(max_length=100)),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="topgun.address"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pilot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("license_number", models.IntegerField(unique=True)),
                ("institution_name", models.CharField(max_length=30)),
                (
                    "instructor_data",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="topgun.instructordata",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="topgun.user"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "grade",
                    models.CharField(
                        choices=[
                            ("A", "Excellent"),
                            ("B", "Satisfactory"),
                            ("C", "Mediocre"),
                            ("D", "Insufficient"),
                            ("F", "Failure"),
                        ],
                        max_length=1,
                    ),
                ),
                (
                    "instructor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instructor",
                        to="topgun.pilot",
                    ),
                ),
                (
                    "pilot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pilot",
                        to="topgun.pilot",
                    ),
                ),
            ],
        ),
    ]
