# Generated by Django 4.2.1 on 2023-05-23 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("topgun", "0002_alter_pilot_license_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pilot",
            name="instructor_data",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="topgun.instructordata",
            ),
        ),
    ]
