# Generated by Django 4.2.1 on 2023-05-25 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topgun', '0003_alter_pilot_instructor_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='grade',
            field=models.CharField(choices=[('A', 'Excellent'), ('B', 'Satisfactory'), ('C', 'Mediocre'), ('D', 'Insufficient'), ('F', 'Failure')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='instructor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instructor', to='topgun.pilot'),
        ),
    ]
