# Generated by Django 4.2.1 on 2023-05-25 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topgun', '0004_alter_flight_grade_alter_flight_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='end_date',
        ),
        migrations.AddField(
            model_name='flight',
            name='duration',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
