# Generated by Django 4.2.1 on 2023-05-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("topgun", "0005_remove_flight_end_date_flight_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flight",
            name="duration",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="pilot",
            name="license_number",
            field=models.PositiveIntegerField(null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="flight",
            constraint=models.CheckConstraint(
                check=models.Q(("duration__range", (1, 12))),
                name="flight_duration_range",
            ),
        ),
    ]
